apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackapp-processamento-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackapp-processamento
  template:
    metadata:
      name: jackapp-processamento
      labels:
        app: jackapp-processamento
    spec:
      automountServiceAccountToken: false
      containers:
      - name: jackapp-processamento-container
        image: brunomoreirareis/jackapp-processamento:latest
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
            ephemeral-storage: "2Gi"
          requests:
            memory: "500Mi"
            cpu: "250m"
            ephemeral-storage: "2Gi"
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: jackapp-processamento-configmap
            optional: true
        volumeMounts:
        - name: jackapp-processamento-storage
          mountPath: /data
      volumes:
      - name: jackapp-processamento-storage
        emptyDir: {}