apiVersion: v1
kind: ConfigMap
metadata:
  name: jackapp-processamento-configmap
data:
  AWS_REGION: us-east-1
  AWS_ENDPOINT: http://localhost:4566/
  SQS_QUEUE_URL: http://localhost:4566/000000000000/VideoProcessingQueue
  SNS_STATUS_TOPIC_ARN: arn:aws:sns:us-east-1:000000000000:VideoStatusTopic
  SNS_ERROR_TOPIC_ARN: arn:aws:sns:us-east-1:000000000000:VideoErrorTopic
  S3_BUCKET_NAME: video-processing-bucket
  AWS_SESSION_TOKEN: token