apiVersion: v1
kind: Service
metadata:
  name: svc-challenge5-app-status
spec:
  type: LoadBalancer
  selector:
    app: challenge5-app-status
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
